# Generated by Django 2.2.8 on 2020-06-09 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_item_discout_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='discout_price',
            new_name='discount_price',
        ),
    ]
