# Generated by Django 2.2.8 on 2020-06-09 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200609_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='This is a test description ndcuhfcnlndclkamcnnclnl11'),
            preserve_default=False,
        ),
    ]
